{% set name = "zopfli" %}
{% set version = "0.1.3" %}
{% set bundle = "zip" %}
{% set hash_type = "sha256" %}
{% set hash = "ecb69a56bb4a6b8e7f6aea25d058a9546243885aef9b232ddbbdcc35ab5fcd6e" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain

  run:
    - python

test:
  imports:
    - zopfli

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache 2.0
  license_family: Apache
  summary: 'Zopfli module for python'
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - pmlandwehr
