{% set name = "zopfli" %}
{% set version = "0.1.7" %}
{% set bundle = "zip" %}
{% set hash = "512892714f0e3dcc9a77222cb509ed519f41ce2b92467e47a4b406a23b48561a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - zopfli

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache 2.0
  license_family: Apache
  summary: 'Zopfli module for python'
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
