{% set name = "zopfli" %}
{% set version = "0.1.6" %}
{% set bundle = "zip" %}
{% set hash_type = "sha256" %}
{% set hash = "ed2293c11c2685bbd70bad0103285279406a77622e06de794d59c2180fecaa6a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - zopfli

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache 2.0
  license_family: Apache
  summary: 'Zopfli module for python'
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
