{% set name = "zopfli" %}
{% set version = "0.1.4" %}
{% set hash_type = "sha256" %}
{% set hash = "95cdbadb8732ef0881aa310079e324c22a800d59ddd44456a1cddb1d42744b62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - toolchain

  run:
    - python

test:
  imports:
    - zopfli

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache 2.0
  license_family: Apache
  summary: 'Zopfli module for python'
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - pmlandwehr
