{% set name = "zopfli" %}
{% set version = "0.1.8" %}
{% set bundle = "zip" %}
{% set hash = "8b977dc07e3797907ab59e08096583bcd0b7e6c739849fbbeec09263f6356623" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - zopfli

about:
  home: https://github.com/obp/zopfli
  license_file: COPYING
  license: Apache-2.0
  license_family: Apache
  summary: Zopfli module for python
  dev_url: https://github.com/obp/zopfli

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
