travis:
  secure:
    BINSTAR_TOKEN: om0mxWDeOWeVfIXd2b0wiJ2f4ZX8pkZUKRDRfJYkptey7AtTWsNZsMyArIoG/7vF/6VAb3JXAl1SLJ0eQZrlLjyorskx3lx/POr+DZnV/K9QKR5jvwryFctA+Q4Q6c/FinlhJalaFx10qI9f1ljdFosyK9yPtb2Fb9vpWHrBwAoEcmJDmdRQQqF31wC4Ub9TJ/itz8ciA0+bbArIlO11EL4G7g0I9w5o2xPXKCWAj3xfkIDzlZ/7ISUbXOC5X4Ul8MTr3j7KBXZvgv6wRAzZcIO7dmv+y5HwyzPfJRMU3STz+ZYgDXF9ywrGpdN0ffTm+AQzlCxw2RIEkYjfNl415JPlQ4BDgBbsyosn2HfA6vob2s1R/D5uSmg0k/CLaWdYqsq+j3H3LAhAQn4445xdlNXUhYNRmpw1prhd9hvdJ/v+Xj44Vxqe61HOfCTa6nWTCNkUdFfn50ykL2+u/NJzvVQ4rzBmNGuSBiCksEtBC+M8VcUOIZUl1v19EG0e8XheGFCiygeH1Suf7u9Snbz+taB808ZR7E3sXJn3gyOXHiw5DnYIY6Vko3jVFZUHTwYD9YjSvGvPSe1nWtIdXXT773YXWmf+k+zVqTCK0xCzQ0OXrKR+LAn3VHY6Kw4ZFVCC7K1iYVS6Hewwdxr8IREhyfOg9YaiwbFAU4bqjvdDdcw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
