travis:
  secure:
    BINSTAR_TOKEN: mRdLwefFUcm7A1Z3qvDCvFETUuMv4A/NbqNbZy1faCXl1z3zXWJFQxJWPA5rCFkGvV036uhXRukFReT6x0ct/KxQmU5ocM0pA1i2KI+mdpdX+rHvNDJgoSWECDMrfBZ/4PCmB4D/PKbJlLZ14f94zs97hCIKm714+OuXkI0U2r+aY+SnFjVR3xg44G6G9kZ84CF8Wd8YqKGGHnuuwR1EBOxKBoiHzTtQjw6v4qAcC5y2uZWD8op9YtvyG1oS0bkaukHCHAX5v/WbXEtvejvxiZQh2sUVIwCGjikMNVkN6RLbyW3Z9nLKFzGrPtbGsafjLtpDw0XeOxaxsBvNQij5w8raPCbPuAydFWkPX6QdkghamFvdzpUx4qJHBHeht2T8jMUzwhAGk2fovbQZf5mLNrf3cFjdaANVHywLMPGewp1UD8etVG+R03L1OuRtDZEoMNiQ5PEAg1GBqKq6N5cLKfxJ5IhsWwhXgYJKHzlytLIx80y/EGX8aPHVIy8C7iceahIeU1yWIqNkzWrN4tuSZRup1AcpZK+u5ZeWfrgL6x9LpjnpeViTtCVhDfH+yUSLF4xCfuf9k6Dg2HytVkmYEY8rBRA1gUyeb6Gl8038PfQ9HoluOPLLd4AqN64sw+ISGX8t18yW0ryf5wBcT3TC8G8jASw2NieS/5u4XBL4zM8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
